### ISSUE TITLE
typescript parse problem

### ISSUE THREAD

**Issue by GaborTorma** [antfu/eslint-config#286]
### Describe the bug

Hi,
If I use the following configuration in VS Code with Nuxt3: 
```
// eslint.config.js
import antfu from '@antfu/eslint-config'
export default antfu({
  typescript: {
    tsconfigPath: './tsconfig.json',
  },
})
```
Sometimes I got error message and non consistent formating.

You can check this in the video.

### Reproduction

https://app.screencast.com/w5tBJlG8l0nm4

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (56) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
    Memory: 29.06 GB / 62.78 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    pnpm: 8.9.0 - /usr/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TouchSek** [comment]
Same +1

**Comment by Dimava** [comment]
@GaborTorma could you show tsconfig contents?

**Comment by GaborTorma** [comment]
I found the problem. The error message shows when we have app.config.ts file for nuxt.
You can reproduce it here: https://stackblitz.com/edit/nuxt-starter-m2hxjw?file=pages%2Findex.vue,.vscode%2Fsettings.json,package.json,app.vue,app.config.ts,README.md

**Comment by GaborTorma** [comment]
Any ts file in root and you get the error messages.

**Comment by GaborTorma** [comment]
Or any js and mjs.

**Comment by antfu** [comment]
This looks like a general typescript-eslint configure issue, where they already provide the ways to fix/workaround this issue doesn't it? I am not sure if any thing we could improve on our side

**Comment by GaborTorma** [comment]
Maybe can you provide a workaround solution for this problem?

**Comment by GaborTorma** [comment]
I found the solution:
```ts
// eslint.config.ts
import antfu from '@antfu/eslint-config'

export default antfu({
  typescript: {
    tsconfigPath: 'tsconfig.json',
    parserOptions: {
      extraFileExtensions: ['.vue'],
    },
  },
})
```
Maybe you can add this parseOptions when vue detected or extend the documentation with this options.

**Comment by GaborTorma** [comment]
Maybe you need to add the parseOptions to the typscript Options definition:
![Snag_142e0680](https://github.com/antfu/eslint-config/assets/11255009/0fd3f0dc-5ec2-46be-9fb2-678f80214729)

**Comment by antfu** [comment]
Beta 28 should fix this. Thanks

**Comment by squirmy** [comment]
Hey - I think I have a related problem. I just tried the latest release and it's still an issue.

When adding the:
```
{
  typescript: {
    tsconfigPath: 'tsconfig.json',
  },
}
```

I get the following error:
```
/Users/squirmy/code/dev.squirmy/packages/website/vite.config.js
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/vite.config.js` using `parserOptions.project`: /users/squirmy/code/dev.squirmy/packages/website/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
```

It's also happening for `.cjs` files. Is there a way to tell eslint not include these for typescript? All three of the options eslint gives don't seem to make much sense to me for this. Am i configuring eslint incorrectly somehow?

**Comment by GaborTorma** [comment]
> Beta 28 should fix this. Thanks

Works well. Thanks!

**Comment by web-dev-sam** [comment]
For people ending up here because of `Parser: (unknown)` this solved it for me:
```
typescript: {
  parserOptions: {
    projectService: true,
    tsconfigRootDir: import.meta.dirname,
  }
}
```
